# IMAP Message Filter Configuration Example
# Copy this file to config.yaml and update with your settings

imap:
  host: "imap.gmail.com"  # Your IMAP server hostname
  port: 993               # IMAP port (993 for SSL, 143 for non-SSL)
  username: "your-email@gmail.com"  # Your email address
  password: "your-app-password"     # Your password or app password
  use_ssl: true           # Use SSL/TLS connection
  timeout: 30             # Connection timeout in seconds

logging:
  level: "INFO"           # Logging level: DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: null              # Log file path (null for console only)

# Example for Gmail with App Password:
# imap:
#   host: "imap.gmail.com"
#   port: 993
#   username: "your-email@gmail.com"
#   password: "your-16-character-app-password"
#   use_ssl: true
#   timeout: 30

# Example for Outlook/Hotmail:
# imap:
#   host: "outlook.office365.com"
#   port: 993
#   username: "your-email@outlook.com"
#   password: "your-password"
#   use_ssl: true
#   timeout: 30

# Example for Yahoo:
# imap:
#   host: "imap.mail.yahoo.com"
#   port: 993
#   username: "your-email@yahoo.com"
#   password: "your-app-password"
#   use_ssl: true
#   timeout: 30
